<?php
/**
 * @var \ClusterifyAI\Chatbot\Block\Category\Guide $block
 * @var \Magento\Framework\Escaper $escaper
 */

if ($block->isFeatureEnabled()):
    $guideValue = $block->getGuideAttributeValue();
    if (!empty($guideValue)):
?>
<div id="clusterify-chatbot-guide-field" hidden class="hidden" aria-hidden="true">
    <?= /* @noEscape */ nl2br($escaper->escapeHtml($guideValue)) ?>
</div>
<?php 
    endif;
endif;
?>
